name: CI Vulnerability Scans - template-only-app

on:
  push:
    branches:
      - main
    paths:
      - template-only-app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-template-only-app-vulnerability-scans.yml
  pull_request:
    paths:
      - template-only-app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-template-only-app-vulnerability-scans.yml

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: template-only-app
